
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "EQ FLOATLIT GE ID INT INTLIT LE NEQ RETURN STR WHILE\nRelation : Relation RelOp Addition\n    | Addition\n\nRelOp : '<' \n    | LE \n    | '>' \n    | GE\n\nAddition : Addition AddOp Term\n    | Term\n\nAddOp : '+' \n    | '-'\n\nTerm : Term MulOp Factor\n    | Factor\n\nPrimary : ID \n    | INTLIT \n    | FLOATLIT \n    | '(' Addition ')'\n\nUnaryOp : '-'\n    | '!'\n\nMulOp : '*' \n    | '/' \n    | '%'\n\nFactor : UnaryOp Primary\n    | Primary\n"
    
_lr_action_items = {'-':([0,2,3,4,6,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,],[7,20,-8,-12,-23,-13,-14,-15,7,7,-3,-4,-5,-6,7,-9,-10,7,-19,-20,-21,-22,20,20,-7,-11,-16,]),'!':([0,12,13,14,15,16,17,18,19,20,21,22,23,24,],[8,8,8,-3,-4,-5,-6,8,-9,-10,8,-19,-20,-21,]),'ID':([0,5,7,8,12,13,14,15,16,17,18,19,20,21,22,23,24,],[9,9,-17,-18,9,9,-3,-4,-5,-6,9,-9,-10,9,-19,-20,-21,]),'INTLIT':([0,5,7,8,12,13,14,15,16,17,18,19,20,21,22,23,24,],[10,10,-17,-18,10,10,-3,-4,-5,-6,10,-9,-10,10,-19,-20,-21,]),'FLOATLIT':([0,5,7,8,12,13,14,15,16,17,18,19,20,21,22,23,24,],[11,11,-17,-18,11,11,-3,-4,-5,-6,11,-9,-10,11,-19,-20,-21,]),'(':([0,5,7,8,12,13,14,15,16,17,18,19,20,21,22,23,24,],[12,12,-17,-18,12,12,-3,-4,-5,-6,12,-9,-10,12,-19,-20,-21,]),'$end':([1,2,3,4,6,9,10,11,25,27,28,29,30,],[0,-2,-8,-12,-23,-13,-14,-15,-22,-1,-7,-11,-16,]),'<':([1,2,3,4,6,9,10,11,25,27,28,29,30,],[14,-2,-8,-12,-23,-13,-14,-15,-22,-1,-7,-11,-16,]),'LE':([1,2,3,4,6,9,10,11,25,27,28,29,30,],[15,-2,-8,-12,-23,-13,-14,-15,-22,-1,-7,-11,-16,]),'>':([1,2,3,4,6,9,10,11,25,27,28,29,30,],[16,-2,-8,-12,-23,-13,-14,-15,-22,-1,-7,-11,-16,]),'GE':([1,2,3,4,6,9,10,11,25,27,28,29,30,],[17,-2,-8,-12,-23,-13,-14,-15,-22,-1,-7,-11,-16,]),'+':([2,3,4,6,9,10,11,25,26,27,28,29,30,],[19,-8,-12,-23,-13,-14,-15,-22,19,19,-7,-11,-16,]),')':([3,4,6,9,10,11,25,26,28,29,30,],[-8,-12,-23,-13,-14,-15,-22,30,-7,-11,-16,]),'*':([3,4,6,9,10,11,25,28,29,30,],[22,-12,-23,-13,-14,-15,-22,22,-11,-16,]),'/':([3,4,6,9,10,11,25,28,29,30,],[23,-12,-23,-13,-14,-15,-22,23,-11,-16,]),'%':([3,4,6,9,10,11,25,28,29,30,],[24,-12,-23,-13,-14,-15,-22,24,-11,-16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Relation':([0,],[1,]),'Addition':([0,12,13,],[2,26,27,]),'Term':([0,12,13,18,],[3,3,3,28,]),'Factor':([0,12,13,18,21,],[4,4,4,4,29,]),'UnaryOp':([0,12,13,18,21,],[5,5,5,5,5,]),'Primary':([0,5,12,13,18,21,],[6,25,6,6,6,6,]),'RelOp':([1,],[13,]),'AddOp':([2,26,27,],[18,18,18,]),'MulOp':([3,28,],[21,21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Relation","S'",1,None,None,None),
  ('Relation -> Relation RelOp Addition','Relation',3,'p_Relation','clite.py',90),
  ('Relation -> Addition','Relation',1,'p_Relation','clite.py',91),
  ('RelOp -> <','RelOp',1,'p_RelOp','clite.py',96),
  ('RelOp -> LE','RelOp',1,'p_RelOp','clite.py',97),
  ('RelOp -> >','RelOp',1,'p_RelOp','clite.py',98),
  ('RelOp -> GE','RelOp',1,'p_RelOp','clite.py',99),
  ('Addition -> Addition AddOp Term','Addition',3,'p_Addition','clite.py',104),
  ('Addition -> Term','Addition',1,'p_Addition','clite.py',105),
  ('AddOp -> +','AddOp',1,'p_AddOp','clite.py',110),
  ('AddOp -> -','AddOp',1,'p_AddOp','clite.py',111),
  ('Term -> Term MulOp Factor','Term',3,'p_Term','clite.py',116),
  ('Term -> Factor','Term',1,'p_Term','clite.py',117),
  ('Primary -> ID','Primary',1,'p_Primary','clite.py',122),
  ('Primary -> INTLIT','Primary',1,'p_Primary','clite.py',123),
  ('Primary -> FLOATLIT','Primary',1,'p_Primary','clite.py',124),
  ('Primary -> ( Addition )','Primary',3,'p_Primary','clite.py',125),
  ('UnaryOp -> -','UnaryOp',1,'p_UnaryOp','clite.py',130),
  ('UnaryOp -> !','UnaryOp',1,'p_UnaryOp','clite.py',131),
  ('MulOp -> *','MulOp',1,'p_MulOp','clite.py',136),
  ('MulOp -> /','MulOp',1,'p_MulOp','clite.py',137),
  ('MulOp -> %','MulOp',1,'p_MulOp','clite.py',138),
  ('Factor -> UnaryOp Primary','Factor',2,'p_Factor','clite.py',143),
  ('Factor -> Primary','Factor',1,'p_Factor','clite.py',144),
]
