
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "ID INTLIT\nExpression : Expression '+' Term\n           | Expression '-' Term\n           | Term\n\nTerm : Term '*' Factor\n     | Term '/' Factor\n     | Term '%' Factor\n     | Factor\n\nFactor : INTLIT\n       | '(' Expression ')'\n"
    
_lr_action_items = {'INTLIT':([0,5,6,7,8,9,10,],[4,4,4,4,4,4,4,]),'(':([0,5,6,7,8,9,10,],[5,5,5,5,5,5,5,]),'$end':([1,2,3,4,12,13,14,15,16,17,],[0,-3,-7,-8,-1,-2,-4,-5,-6,-9,]),'+':([1,2,3,4,11,12,13,14,15,16,17,],[6,-3,-7,-8,6,-1,-2,-4,-5,-6,-9,]),'-':([1,2,3,4,11,12,13,14,15,16,17,],[7,-3,-7,-8,7,-1,-2,-4,-5,-6,-9,]),')':([2,3,4,11,12,13,14,15,16,17,],[-3,-7,-8,17,-1,-2,-4,-5,-6,-9,]),'*':([2,3,4,12,13,14,15,16,17,],[8,-7,-8,8,8,-4,-5,-6,-9,]),'/':([2,3,4,12,13,14,15,16,17,],[9,-7,-8,9,9,-4,-5,-6,-9,]),'%':([2,3,4,12,13,14,15,16,17,],[10,-7,-8,10,10,-4,-5,-6,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Expression':([0,5,],[1,11,]),'Term':([0,5,6,7,],[2,2,12,13,]),'Factor':([0,5,6,7,8,9,10,],[3,3,3,3,14,15,16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Expression","S'",1,None,None,None),
  ('Expression -> Expression + Term','Expression',3,'p_Expression','analisis.py',31),
  ('Expression -> Expression - Term','Expression',3,'p_Expression','analisis.py',32),
  ('Expression -> Term','Expression',1,'p_Expression','analisis.py',33),
  ('Term -> Term * Factor','Term',3,'p_Term','analisis.py',43),
  ('Term -> Term / Factor','Term',3,'p_Term','analisis.py',44),
  ('Term -> Term % Factor','Term',3,'p_Term','analisis.py',45),
  ('Term -> Factor','Term',1,'p_Term','analisis.py',46),
  ('Factor -> INTLIT','Factor',1,'p_Factor','analisis.py',56),
  ('Factor -> ( Expression )','Factor',3,'p_Factor','analisis.py',57),
]
